<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>b10616f6-6428-49f7-8ed5-356449bb66f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginLoginWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginLoginWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15523a63-5d7b-42ea-90b2-bfd3cbe05272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>88d12477-63b3-414e-9d1d-cf4dbfded8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginLoginWrap</value>
      <webElementGuid>8f4ca46b-1b6a-4704-8dc2-3a2ebd574922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f01ca18e-fcba-44d1-8025-78b5f4fe770b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FieldRenderers__Input-sc-1qxt7mw-5 hTakoO</value>
      <webElementGuid>2b3b8141-530e-4f89-be28-fb81de011c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginLoginWrap&quot;)</value>
      <webElementGuid>fc24848f-49ac-4ef5-9a4f-c1c6c00bfcdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginLoginWrap']</value>
      <webElementGuid>6fd3b1c4-0a54-4851-9478-7aa880371e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/form/div[2]/div/input</value>
      <webElementGuid>968287e0-7f85-405c-9356-b5f2974e2a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>68fac07d-0c3c-44e0-9269-48bc445263be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginLoginWrap' and @name = 'password']</value>
      <webElementGuid>4515cb21-6c07-44af-88e4-b78f21f59edc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
