<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_login</name>
   <tag></tag>
   <elementGuidId>1a2de84f-d73d-4c33-95c2-0c474e44ffc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a50ec1fc-7695-4751-8f65-19962006136e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>478e93b2-7dcc-4173-afc8-1ac4f93cbf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginUsername</value>
      <webElementGuid>5bf2ab56-48f1-40d1-8703-91a3d106e81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>23358a61-5f90-48c7-8704-d9af5b83003c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FieldRenderers__Input-sc-1qxt7mw-5 hTakoO</value>
      <webElementGuid>4b497425-c728-477f-8c64-f26fb9abede4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginUsername&quot;)</value>
      <webElementGuid>c590e056-5c4b-4e4f-b55c-8ea5626c9de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginUsername']</value>
      <webElementGuid>55eb3543-cc96-4590-8c6b-fb554faabde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/form/div/div/input</value>
      <webElementGuid>3af92775-f210-4389-a7df-a2f5b9f7a5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>679e26f2-4554-4b1a-b9b4-f94124abc711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'loginUsername' and @name = 'login']</value>
      <webElementGuid>3630f012-1398-4c0e-a687-7157ec14dd2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
