<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MODS</name>
   <tag></tag>
   <elementGuidId>3c3ccf70-b48f-4f0d-af00-1c663ff06229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SiteNav']/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>326c6b54-39af-41cc-bd0b-dc66f45a8eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/mods</value>
      <webElementGuid>50a9711b-b5a7-497b-a0d3-5d19d43a3a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--main</value>
      <webElementGuid>bcc21e70-7a0a-437a-a310-c7ed518e50e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            MODS 
          </value>
      <webElementGuid>45a9a894-46f9-476e-a0d0-f27aac1a0229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteNav&quot;)/li[6]/a[@class=&quot;site-nav__link site-nav__link--main&quot;]</value>
      <webElementGuid>2f6e9106-b755-4fd1-9765-8ef5f3c1e230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SiteNav']/li[6]/a</value>
      <webElementGuid>2228f91b-3aab-4e75-8ee2-a1e29459d299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MODS')]</value>
      <webElementGuid>0638e33b-2883-40e4-8c1c-bcef9103123d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KITS'])[1]/following::a[1]</value>
      <webElementGuid>98deeec3-0f63-473a-8f25-18e15e542809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COILS'])[1]/following::a[2]</value>
      <webElementGuid>e0e71108-10f5-4cbe-88b2-2843e3c990ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TANKS'])[1]/preceding::a[1]</value>
      <webElementGuid>b2f514ce-fb1c-48f9-843a-bbfc3da139f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BATTERIES &amp; CHARGERS'])[1]/preceding::a[2]</value>
      <webElementGuid>590a1479-f300-40c9-8bce-6cc8cb62a71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MODS']/parent::*</value>
      <webElementGuid>902e6fd1-16b9-45f5-ab37-58230f01cbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collections/mods')]</value>
      <webElementGuid>e5726b5a-ab43-400b-8e17-625352c67149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>051969a5-9f22-4f2b-b15a-5c31d37f64ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/mods' and (text() = '
            MODS 
          ' or . = '
            MODS 
          ')]</value>
      <webElementGuid>f5b38100-1213-4b86-8b8d-9892fc592d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
