<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_COILS</name>
   <tag></tag>
   <elementGuidId>dea466ea-4d46-4531-bf9b-299019b94870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SiteNav']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a55d83a-2aa5-4c95-b553-815f74aa37c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/coils-1</value>
      <webElementGuid>abbdd7e2-cc1c-4fac-ae0e-64773d65ed9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--main</value>
      <webElementGuid>92b4da22-d2a1-46b0-8a4e-66ad29c83d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            COILS
          </value>
      <webElementGuid>5c0fe7d2-860c-44cd-946b-36a6a4acdc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteNav&quot;)/li[4]/a[@class=&quot;site-nav__link site-nav__link--main&quot;]</value>
      <webElementGuid>deb75b27-9160-4d3e-ab36-4c808f4f8ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SiteNav']/li[4]/a</value>
      <webElementGuid>5fcc5951-0de0-49c0-a1b4-373397cb313b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'COILS')]</value>
      <webElementGuid>4d792c27-8b6c-4f24-999e-e8ed9f2a0bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERSTATE &amp; INTERNATIONAL E-LIQUIDS'])[1]/following::a[1]</value>
      <webElementGuid>e698bc53-3399-458f-a31d-d19166a020c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WE DO NOT SELL NICOTINE AS IT IS ILLEGAL TO SELL NICOTINE IN AUSTRALIA'])[1]/following::a[5]</value>
      <webElementGuid>7bc71550-d242-4e0b-ab6b-cda0aef1a5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KITS'])[1]/preceding::a[1]</value>
      <webElementGuid>80ac77bc-0e2a-4036-be8f-8777ae856e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MODS'])[1]/preceding::a[2]</value>
      <webElementGuid>57372127-c361-470c-a2bf-eb9efa941064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COILS']/parent::*</value>
      <webElementGuid>7a3fdd2e-80a5-42f4-a0c2-f82894ad3334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collections/coils-1')]</value>
      <webElementGuid>e4fc56fd-445b-4b60-a69b-6a82fe41defc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[4]/a</value>
      <webElementGuid>a602d259-82f2-46db-946a-906245d48c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/coils-1' and (text() = '
            COILS
          ' or . = '
            COILS
          ')]</value>
      <webElementGuid>db9348c0-8a37-430e-9c38-5f3ffec04fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
