<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_WE DO NOT SELL NICOTINE AS IT IS ILLEGA_6e7cf5</name>
   <tag></tag>
   <elementGuidId>f661ed3f-21ce-4bd1-97b8-c7e911c93b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.js.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-nov-header']/div/header/div[3]/div/div/div/div/div/h1/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49994cb7-631a-4a70-8bdd-d41624ecace1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js img-fluid</value>
      <webElementGuid>eeefd73f-b7b5-47d5-9f2a-2a3853a00ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdn.shopify.com/s/files/1/2663/3040/files/white_transparent_logo_205x_d1a5015d-198f-4b1b-8840-ce15e7fed7d9_350x.webp?v=1651645014</value>
      <webElementGuid>a5a2316b-635f-4500-bf37-89a4d690772a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>VAPE STATION</value>
      <webElementGuid>b1ca52f0-74c0-421e-b884-52bd41c6f3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-nov-header&quot;)/div[1]/header[@class=&quot;site-header&quot;]/div[@class=&quot;header-top d-none d-md-block&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;hd_ct_tl col-xl-7 col-lg-6 col-md-7&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;contentsticky_logo&quot;]/h1[@class=&quot;h2 site-header__logo mb-0&quot;]/a[@class=&quot;site-header__logo-image&quot;]/img[@class=&quot;js img-fluid&quot;]</value>
      <webElementGuid>7107419d-d777-4505-a53c-c625e29462e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-nov-header']/div/header/div[3]/div/div/div/div/div/h1/a/img</value>
      <webElementGuid>623de908-99f8-4853-9f05-e49e8f811c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='VAPE STATION']</value>
      <webElementGuid>384cae92-0456-49bd-914c-b047b46ecad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/a/img</value>
      <webElementGuid>e29f3c05-58b3-4ede-9e91-56ddaaed3eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdn.shopify.com/s/files/1/2663/3040/files/white_transparent_logo_205x_d1a5015d-198f-4b1b-8840-ce15e7fed7d9_350x.webp?v=1651645014' and @alt = 'VAPE STATION']</value>
      <webElementGuid>5bc01483-bbf9-4948-ade5-da7f5f01b4b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
