<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WE DO NOT SELL NICOTINE AS IT IS ILLE_d0ecbb</name>
   <tag></tag>
   <elementGuidId>3bb7cd25-9a3a-4355-89fa-831133eaadc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_widget > form.search-header-inline.search > input[name=&quot;q&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='q'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08be206c-cf9e-4aec-80b8-8eebbbfac961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-header__input</value>
      <webElementGuid>8f10e527-d327-471f-806e-ed8f65791f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>f1ad357e-dd9c-4e05-b761-bd6d9e550abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>a23d394a-1e19-4409-a67b-2f67fc26748b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your keyword</value>
      <webElementGuid>bac5632d-4c71-4320-b604-272ef5e46183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search your product</value>
      <webElementGuid>c15a1944-a8d8-452e-8656-6bba4dc379e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eff7f001-c7ae-4175-8738-f0f025ea0aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_widget&quot;)/form[@class=&quot;search-header-inline search&quot;]/input[@class=&quot;search-header__input&quot;]</value>
      <webElementGuid>b2525e14-70a4-49d4-9dbc-5c1f2f75bd59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='q'])[2]</value>
      <webElementGuid>7c4d9fdd-cbff-4733-ad4e-f1159762c060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_widget']/form/input[2]</value>
      <webElementGuid>ea52feac-8283-4a52-bf8a-b348a9c6a656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/form/input[2]</value>
      <webElementGuid>0e796555-4031-4574-b879-461fc7075110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 'q' and @placeholder = 'Enter your keyword']</value>
      <webElementGuid>a4b87153-7a12-4b76-8622-7fab5c38b83a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
