<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue with Apple</name>
   <tag></tag>
   <elementGuidId>79bd3400-ede6-4170-b72b-b34789b3f24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='apple-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apple-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8759d207-72cc-4cc9-8f1b-b433232cdb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>551cf0a0-9ad8-4eb7-adcd-611770b0a3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c187d9ed-c269-47ba-9977-3443aedefe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apple-register</value>
      <webElementGuid>94379cb6-5b0e-4af5-ad88-859fd6e73da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>apple-register</value>
      <webElementGuid>6cb7929e-aaef-436f-9183-eefdda8b0630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://appleid.apple.com/auth/authorize?redirect_uri=https%3A%2F%2Fwww.meetup.com%2Fties2%2F&amp;state=returnUri%3Dhttps%253A%252F%252Fwww.meetup.com%252Fregister%252F%253Fmethod%253Dsocial%2526returnUri%253Dhttps%25253A%25252F%25252Fwww.meetup.com%25252Fhome%26register%3Dtrue&amp;client_id=com.meetup.web&amp;response_type=code%20id_token&amp;scope=name%20email&amp;response_mode=form_post</value>
      <webElementGuid>7721a7b6-76cd-4060-9f21-26b18b1dd634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>register-with-apple-btn</value>
      <webElementGuid>890c0ac7-a70f-4390-9105-5bb35965d3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>register-with-apple-option</value>
      <webElementGuid>1dcdd463-ea86-4361-b004-6cee091eb200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full font-normal border border-gray6 h-13 pl-4 rounded-lg flex flex-row items-center justify-between cursor-pointer xs:no-underline hover:no-underline c1g28vq9</value>
      <webElementGuid>3105a134-d33b-46f1-b6a5-31e4a3608a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with Apple</value>
      <webElementGuid>202df89a-7b9d-488b-a64a-a00df211b0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apple-register&quot;)</value>
      <webElementGuid>671791d1-7954-4ccd-b9ee-318e23e3bc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='apple-register']</value>
      <webElementGuid>d82f40b5-c570-48d8-ad21-54f7951e1e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/div/div/div/section/form/div[3]/a[3]</value>
      <webElementGuid>ae1a2c0b-443e-4005-a876-3e063e82e1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue with Apple')]</value>
      <webElementGuid>05e0a5c6-2fff-4d37-a717-84341e9d856c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Google'])[1]/following::a[1]</value>
      <webElementGuid>081b8ac8-938a-48b0-a238-d22dcffb155a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Facebook'])[1]/following::a[2]</value>
      <webElementGuid>464583ac-6bf8-4724-b15b-ec3ee6033635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up with email'])[1]/preceding::a[1]</value>
      <webElementGuid>f5bc2c45-2613-4ed0-89f3-46e44552cf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'apple-register', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>e8727ba4-3ef0-48fe-a26d-0f7857480dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue with Apple']/parent::*</value>
      <webElementGuid>90e5d20c-428f-4fad-bccd-89b0bccc8330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://appleid.apple.com/auth/authorize?redirect_uri=https%3A%2F%2Fwww.meetup.com%2Fties2%2F&amp;state=returnUri%3Dhttps%253A%252F%252Fwww.meetup.com%252Fregister%252F%253Fmethod%253Dsocial%2526returnUri%253Dhttps%25253A%25252F%25252Fwww.meetup.com%25252Fhome%26register%3Dtrue&amp;client_id=com.meetup.web&amp;response_type=code%20id_token&amp;scope=name%20email&amp;response_mode=form_post')]</value>
      <webElementGuid>f9884cf9-1a82-4a0a-82e5-db68ddee21f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[3]</value>
      <webElementGuid>01956405-da02-4eb9-8770-ca76be8b2c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'apple-register' and @href = 'https://appleid.apple.com/auth/authorize?redirect_uri=https%3A%2F%2Fwww.meetup.com%2Fties2%2F&amp;state=returnUri%3Dhttps%253A%252F%252Fwww.meetup.com%252Fregister%252F%253Fmethod%253Dsocial%2526returnUri%253Dhttps%25253A%25252F%25252Fwww.meetup.com%25252Fhome%26register%3Dtrue&amp;client_id=com.meetup.web&amp;response_type=code%20id_token&amp;scope=name%20email&amp;response_mode=form_post' and (text() = 'Continue with Apple' or . = 'Continue with Apple')]</value>
      <webElementGuid>713d33d7-fa02-4e2f-8ae2-6c914f95c4c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
