<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign up</name>
   <tag></tag>
   <elementGuidId>477e932f-6316-4a23-a15c-1880dffe3c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='submitRegistrationButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;submitRegistrationButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c33fc78f-c235-45a0-9253-c9f3fdb11fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit-email-registration</value>
      <webElementGuid>c37fa3bf-a907-4ad8-b8ea-37d2f79d9240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1cb190c0-e095-42ca-a25f-bc493abbee1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full ds-font-title-3 h-12 p14rljdx</value>
      <webElementGuid>b0352b59-2940-4cfd-9f1f-75c47a0cb595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitRegistrationButton</value>
      <webElementGuid>638f31ad-af51-4929-9c8b-ae250d3d6615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>register-submit-btn</value>
      <webElementGuid>f50549a3-1287-41bf-9e63-d9425091065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>register-with-email-signup</value>
      <webElementGuid>ba1953d8-622d-4919-8d8b-12c359b7f991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>2e74772d-26f6-4af5-a612-762a6d6f5e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;inset-0 fixed z-modal flex flex-col items-center justify-end sm:justify-center&quot;]/div[@class=&quot;pl-0 pr-0 sm:pl-10 sm:pr-10 a27i9ef hidden relative sm:block bg-white rounded-lg shadow-lg pl-12 pr-10 pt-9 pb-8 z-50 md:max-w-prose max-h-screen overflow-y-auto mcm12el&quot;]/div[@class=&quot;hidden sm:block xmedia&quot;]/div[@class=&quot;flex flex-col items-center px-6 sm:px-0&quot;]/section[@class=&quot;w-full sbdsy28 flex flex-col items-center&quot;]/form[@class=&quot;w-full pt-18 sm:pt-8&quot;]/div[@class=&quot;w-full flex flex-col space-y-6 mb-4 mt-8&quot;]/button[@class=&quot;w-full ds-font-title-3 h-12 p14rljdx&quot;]</value>
      <webElementGuid>d652f5ac-05c4-4790-aad6-b6b4a7a8d7d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='submitRegistrationButton']</value>
      <webElementGuid>67726ec7-16a3-4294-af52-e65a69990ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/div/div/div/section/form/div[2]/button</value>
      <webElementGuid>bd6fad4c-775f-4629-a667-385dce279ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am 18 years of age or older.'])[1]/following::button[1]</value>
      <webElementGuid>092b38a0-9a3f-46c5-97a5-1d2e91db6546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/following::button[2]</value>
      <webElementGuid>90b239da-b5f2-4310-bf4f-cf679c34d095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[2]/preceding::button[1]</value>
      <webElementGuid>3514d624-00b8-4dcd-af82-a2a89dad7904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[2]/preceding::button[1]</value>
      <webElementGuid>13c6e469-0e94-46e1-978a-58db0df55821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>af2efcae-1907-47d8-b70a-3dd49e46f885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'submitRegistrationButton' and (text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>8915d306-fc2e-4f36-bfe9-486b52c719b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
