<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign up with email</name>
   <tag></tag>
   <elementGuidId>99d6481b-aec2-4a95-b061-70efa10e6ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='email-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09d848f0-f316-4eb5-8378-8715a44dca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5645581-8414-45b8-af45-2417403180a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf399d2b-2a98-4fea-9c42-36d30b9530d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-register</value>
      <webElementGuid>b4f3e7e1-6e05-4191-b521-295e594fdd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email-register</value>
      <webElementGuid>d037fd35-4851-4594-a9a3-5dd8e56734be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>register-with-email-option</value>
      <webElementGuid>f7d9d74d-7caa-4654-a9ac-617f2007149b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full font-normal border border-gray6 h-13 pl-4 rounded-lg flex flex-row items-center justify-between cursor-pointer xs:no-underline hover:no-underline c1g28vq9</value>
      <webElementGuid>a4704307-5d56-4155-8a76-6428ce33acfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up with email</value>
      <webElementGuid>d4f90538-df38-437a-84fb-ca8fc4b966c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-register&quot;)</value>
      <webElementGuid>42d2beb7-07c3-46f5-b156-3f3b449be85c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='email-register']</value>
      <webElementGuid>591689b7-248e-4c82-a9a3-2f25cd31a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/div/div/div/section/form/div[3]/div/button</value>
      <webElementGuid>b17fe54e-b51d-405d-bd87-bf36be9cf57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Apple'])[1]/following::button[1]</value>
      <webElementGuid>b07d59a6-3daf-4bdc-b824-d7743f6bf1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Google'])[1]/following::button[1]</value>
      <webElementGuid>d5123127-0dbb-40c5-8d39-99a38f0cc643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'email-register', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>89a158e9-58ca-4a2b-9035-690f6530357e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Preference Center'])[1]/preceding::button[2]</value>
      <webElementGuid>175b2361-73b4-40c4-aff2-dd37b916bb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up with email']/parent::*</value>
      <webElementGuid>51d1d2f3-20be-4cc9-9fa1-753599d550d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>ffde36f1-a1b1-4361-bb6c-da592eb0cf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'email-register' and (text() = 'Sign up with email' or . = 'Sign up with email')]</value>
      <webElementGuid>c717bfa2-4766-47cf-9ebe-907c8bb0ee22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
