<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in</name>
   <tag></tag>
   <elementGuidId>48f446f6-7173-4cef-a2c3-a0f26bcd06f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='submitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;submitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35eb105c-3688-412c-a357-5b3fe65e95ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f18aa01d-315b-452e-8465-78a4ddc7e405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>51f4890b-36e5-44e8-91bc-099b11546c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full ds-font-title-3 h-12 mt-4 p14rljdx</value>
      <webElementGuid>1021600a-33e6-46e9-a8ee-82f6e23d4369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>df523fe6-89b1-4e0e-ae39-41008e66e4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>login-submit-btn</value>
      <webElementGuid>6469d09b-1056-4924-a882-a179012dc67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>login-with-email</value>
      <webElementGuid>f95cba70-8fd5-4da2-a061-f27bec94ebf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>0a09f040-7e44-4936-802c-522b6677e6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;inset-0 fixed z-modal flex flex-col items-center justify-end sm:justify-center&quot;]/div[@class=&quot;pl-0 pr-0 sm:pl-10 sm:pr-10 a27i9ef hidden relative sm:block bg-white rounded-lg shadow-lg pl-12 pr-10 pt-9 pb-8 z-50 md:max-w-prose max-h-screen overflow-y-auto mcm12el&quot;]/div[@class=&quot;hidden sm:block xmedia&quot;]/div[@class=&quot;flex flex-col items-center px-6 sm:px-0&quot;]/section[@class=&quot;w-full sbdsy28 flex flex-col items-center&quot;]/form[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col-reverse md:flex-col items-center space-y-8&quot;]/div[@class=&quot;w-full&quot;]/button[@class=&quot;w-full ds-font-title-3 h-12 mt-4 p14rljdx&quot;]</value>
      <webElementGuid>e5cabe13-8d32-4570-9765-737bb0b6c2cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='submitButton']</value>
      <webElementGuid>1cc62c13-55d3-4001-a3a8-fb210d7d985c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/div/div/div/section/form/div[2]/div/button</value>
      <webElementGuid>c71c6542-7415-4826-9afe-5ee6854ddf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me signed in'])[1]/following::button[1]</value>
      <webElementGuid>735ee3bc-d0cb-4c35-b426-4b28c766bbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password'])[1]/following::button[1]</value>
      <webElementGuid>2fc524ed-9233-4db6-adec-8a53ce458623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/preceding::button[1]</value>
      <webElementGuid>933c4aa4-245c-4473-953a-917b59c6e0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with Facebook'])[1]/preceding::button[1]</value>
      <webElementGuid>a63dffb0-c773-412d-a299-b49dac4b07dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button</value>
      <webElementGuid>567fbc31-92b2-4a73-8f0f-5cdddccc2bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'submitButton' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>25b53d0c-4244-4022-a7c4-39154e88509c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
