<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_location</name>
   <tag></tag>
   <elementGuidId>30ce2d14-e8cf-4acc-8d6b-e314dc99507f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location-typeahead-searchLocation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location-typeahead-searchLocation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d1bee95-6c59-4192-aaf1-f105eb98ab1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>searchLocation</value>
      <webElementGuid>aee41840-fe45-4b70-80af-49c3643c906f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>Location search</value>
      <webElementGuid>05fd59c4-c671-46e4-926f-c37f027af2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appearance-none border p-2 pl-4 border-gray3 outline-none hover:border-gray6 focus:border-viridian hover:z-10 focus:z-10 i1mxuvo4 rounded-l-none w-full w-full sm:rounded border fyw5ej6 l1mhmifi</value>
      <webElementGuid>4203517f-2ed8-4437-97e7-0b64481f5dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Neighborhood or City or zip code</value>
      <webElementGuid>68f04f95-ee71-4bb6-b0d0-cbab99aadc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for location by city or zip code</value>
      <webElementGuid>862a1632-3aab-4a99-bcd3-e6e217140ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location-typeahead-searchLocation</value>
      <webElementGuid>39bea6be-1b4d-4ba0-a18f-889fce1b780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>45fb241e-f2bf-462f-a967-06e29df326a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location-typeahead-searchLocation-menu</value>
      <webElementGuid>c5642e28-a134-4f1a-aafc-e6f0da7ec255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>location-typeahead-searchLocation-label</value>
      <webElementGuid>b15907cb-9380-45d3-a1f7-f7073f732907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3722f665-98ec-49d5-819f-ea49f77899c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location-typeahead-searchLocation&quot;)</value>
      <webElementGuid>8fe95178-57da-496f-92e7-7ed45be22c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location-typeahead-searchLocation']</value>
      <webElementGuid>0c7475f5-c032-473c-9ef6-c5194693ac87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/main/div/div[4]/div/form/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>1e9dff38-257d-412d-91cb-5933f7bd7627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>f9f4da15-c430-4a0a-a8a4-c5d85baf1006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Neighborhood or City or zip code' and @id = 'location-typeahead-searchLocation']</value>
      <webElementGuid>e70b36f8-55c6-49b6-9adc-245d9ccac403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
