<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_keyword</name>
   <tag></tag>
   <elementGuidId>7aa958b0-ceaa-4a35-9890-239bfc7f508e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-keyword-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-keyword-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dc94f52-51f3-417c-a584-de80cdc7a88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-keyword-input</value>
      <webElementGuid>3795b0c9-4445-4d7b-8fd7-b42d9fb0f33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>keywordSearchBar</value>
      <webElementGuid>bf4e0877-a315-433f-93b1-ca60f4022af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>Keyword search</value>
      <webElementGuid>4f686768-cf56-47f9-a813-4510bc5aef68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70d59e80-a426-4320-b3bb-20a307c02f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>617be414-70dd-485d-8832-c6378f748ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for &quot;tennis&quot; or &quot;UX design&quot;</value>
      <webElementGuid>7188b943-2abb-4f57-8749-c228cf70ec99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-t rounded-b-none border border-b-0 sm:border-b sm:rounded border-gray3 fyw5ej6</value>
      <webElementGuid>b341120a-baa1-4034-95c8-e1afcf007fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-keyword-input</value>
      <webElementGuid>1fe6d005-6d67-4a3e-8856-b3cada6d59cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-keyword-input&quot;)</value>
      <webElementGuid>42d961f5-c716-4b9a-bdc2-454feac1c341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-keyword-input']</value>
      <webElementGuid>e12e8e88-6e8d-4f36-a23e-93a5002238ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/main/div/div[4]/div/form/div/div/input</value>
      <webElementGuid>3e0fe235-67f0-42ce-9d8e-56205a7f2ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a77608a8-c868-4268-9d40-b4196ac36a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-keyword-input' and @type = 'text' and @placeholder = 'Search for &quot;tennis&quot; or &quot;UX design&quot;']</value>
      <webElementGuid>a535ee9a-19c5-44c0-8e75-514ec611f093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
