<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Button</name>
   <tag></tag>
   <elementGuidId>9939f7e1-177a-42fe-a066-a95c59d7a9e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27d2fe07-5270-43c1-be66-f29fe5ef8fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>searchBarButton</value>
      <webElementGuid>01288e80-0682-4d70-ba86-f8bb0acc08ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>Search bar</value>
      <webElementGuid>1e76d0a2-a766-447f-bc8b-a246c94c3b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-submit</value>
      <webElementGuid>459222ce-0007-4234-a729-ce0a2fe4ba71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>25833760-bb8a-47e2-bd2f-c7c33b3dcaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-4 h-12 w-full rounded-xl cursor-pointer text-white bg-peach fill-currentColor border-peach font-bold text-xl hover:no-underline focus:no-underline s2z49xj</value>
      <webElementGuid>5afd79d4-b2cf-437a-aa1d-c4bb937a7e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b0545d8a-0da0-421b-9053-3caf7cd63637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;flex flex-col flex-grow z-10&quot;]/main[@class=&quot;flex flex-col items-center flex-grow relative overflow-hidden&quot;]/div[@class=&quot;px-6 sm:px-4 xl:px-0 md:max-w-screen w-full&quot;]/div[@class=&quot;grid lg:grid-cols-2 md:grid-cols-1 mt-20&quot;]/div[@class=&quot;relative mb-6 lg:mb-0 mb-6 lg:mr-8&quot;]/form[1]/div[2]/input[@class=&quot;py-2 px-4 h-12 w-full rounded-xl cursor-pointer text-white bg-peach fill-currentColor border-peach font-bold text-xl hover:no-underline focus:no-underline s2z49xj&quot;]</value>
      <webElementGuid>723af9ff-f86c-4deb-b7c2-84d465aee10f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Search']</value>
      <webElementGuid>57c34390-913f-41b6-88de-21b62ac506ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/main/div/div[4]/div/form/div[2]/input</value>
      <webElementGuid>92226de0-9dd7-4004-b409-6a8973b65d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c5d72212-c8da-4508-9050-d5aa8170b933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>c6e25efd-8f66-42c2-b4cd-7279e9a8b396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
