<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Brisbane, Australia</name>
   <tag></tag>
   <elementGuidId>d8137d21-859e-4134-b6b8-dff7493749ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your location'])[1]/following::li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#undefined0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0d469731-30d7-43bb-8925-7e82cbbe8ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs:text-viridian cursor-pointer p-4 text-gray6</value>
      <webElementGuid>634a17f3-bae2-401c-a71f-391839d48d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c341ef4d-f4a5-4b41-b084-f4bbd486e6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5ccb06a-4eef-4fc7-a648-42eaa60bed7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined0</value>
      <webElementGuid>fc435e50-03e6-41b9-83c2-4ed7e5309edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brisbane, Australia</value>
      <webElementGuid>32869b93-95f6-458d-8681-7fc3e32a15d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined0&quot;)</value>
      <webElementGuid>1c9d0bc8-42d9-4083-8496-00959c07abdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='undefined0']</value>
      <webElementGuid>6f4f4965-adb5-4c15-9196-02940bc70d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='location-typeahead-searchLocation-menu']/li[2]</value>
      <webElementGuid>1da468fa-7971-42a1-9842-3f6b72c5f73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::li[1]</value>
      <webElementGuid>6385068d-172d-47b7-afc7-894546dd6903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your location'])[1]/following::li[2]</value>
      <webElementGuid>a80fef6d-018c-4659-b39d-3a9762e80f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>c0c53e21-4884-46fd-b8fa-6be0273d5070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'undefined0' and (text() = 'Brisbane, Australia' or . = 'Brisbane, Australia')]</value>
      <webElementGuid>ffca3a0f-4667-495b-8aba-ecafa8028d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
