<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TANKS</name>
   <tag></tag>
   <elementGuidId>0efdc2ef-b056-407d-a005-baf2fb00db4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SiteNav']/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>992cf97b-a8ee-4ba4-8e53-b5c850f0ac8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/tanks</value>
      <webElementGuid>73f077e1-8c30-4535-8202-1658989bcaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--main</value>
      <webElementGuid>a834b733-7fcc-4a0f-aa5b-d396a0b1020e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            TANKS 
          </value>
      <webElementGuid>6043cff7-c030-4481-bed9-5416af29258e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteNav&quot;)/li[7]/a[@class=&quot;site-nav__link site-nav__link--main&quot;]</value>
      <webElementGuid>64a285a6-c2b7-4403-aa2d-39b2bd4abb6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SiteNav']/li[7]/a</value>
      <webElementGuid>6ca07483-da55-4fb7-a139-4199b77cb983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TANKS')]</value>
      <webElementGuid>5fb74058-8c22-4180-8dd3-99cc908d976c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MODS'])[1]/following::a[1]</value>
      <webElementGuid>34fb043b-fe52-4b71-b697-ff1c8e73b338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KITS'])[1]/following::a[2]</value>
      <webElementGuid>1269477a-6ad5-4386-9fd2-53d321d01caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BATTERIES &amp; CHARGERS'])[1]/preceding::a[1]</value>
      <webElementGuid>876947f5-ae2a-4914-abec-3ab55a945af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPLACEMENT GLASS'])[1]/preceding::a[2]</value>
      <webElementGuid>5b249aca-eaa2-4258-81a9-93e9f6179194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TANKS']/parent::*</value>
      <webElementGuid>7a671502-2105-4a1b-bff5-667b70a78ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/tanks')])[2]</value>
      <webElementGuid>72047ddd-35ee-4b60-b07d-23b043c93c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>c526bf91-098b-4d77-90f0-afc38310f213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/tanks' and (text() = '
            TANKS 
          ' or . = '
            TANKS 
          ')]</value>
      <webElementGuid>b2c85101-d4c7-40fc-a4cb-902f4f3e62df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
