<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DIY</name>
   <tag></tag>
   <elementGuidId>9ff76545-4a5d-4a3a-bebf-bc5aab16790a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.group_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SiteNav']/li[10]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5365f730-0436-4b77-b510-12bae512af48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group_title</value>
      <webElementGuid>ea425d80-2221-4279-a007-503b158983c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIY</value>
      <webElementGuid>75b5e6d6-8f4d-43e7-8c7c-00ce0901fad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteNav&quot;)/li[@class=&quot;site-nav--has-dropdown menu_mb&quot;]/a[@class=&quot;d-flex&quot;]/div[@class=&quot;group_title&quot;]</value>
      <webElementGuid>28d412e6-d52d-4010-ba45-c307adbc05b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SiteNav']/li[10]/a/div</value>
      <webElementGuid>fb6e3244-b4a7-468e-810d-9e3b3e5665c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPLACEMENT GLASS'])[1]/following::div[1]</value>
      <webElementGuid>36175163-31d4-4144-b0e5-8a8d0f983d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BATTERIES &amp; CHARGERS'])[1]/following::div[1]</value>
      <webElementGuid>a85bf10d-f8f7-43bd-a23d-feb27c812816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIY PRODUCTS'])[1]/preceding::div[1]</value>
      <webElementGuid>9cd9d7ba-53af-4a15-828d-395aac4fb150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIY PREMIUM CONCENTRATES'])[1]/preceding::div[1]</value>
      <webElementGuid>ef3e0cad-51bf-4afe-93d2-1d2d4dac4a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIY']/parent::*</value>
      <webElementGuid>6cf5e686-a66f-49a0-b96f-52d3cc2b448a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>2f2e14e2-e948-4123-ab89-702531868ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DIY' or . = 'DIY')]</value>
      <webElementGuid>d25c5032-9a51-4c7d-a76d-d30b6d5fea93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
