<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KITS</name>
   <tag></tag>
   <elementGuidId>27304ff5-cb6c-4a33-9aa8-bdae96d7f0a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SiteNav']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a56d777b-ff4e-44b6-8e3f-4b8e19a74468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/complete-kits</value>
      <webElementGuid>3ae67838-b88c-4a61-b8ab-a53a49e83c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--main</value>
      <webElementGuid>0ef54094-7084-42ba-9538-bff8b84acc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            KITS
          </value>
      <webElementGuid>093e5821-095a-434e-87ff-d9473352ba0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteNav&quot;)/li[5]/a[@class=&quot;site-nav__link site-nav__link--main&quot;]</value>
      <webElementGuid>5298f4f1-2f29-4b54-b1fb-2b9187d00b28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SiteNav']/li[5]/a</value>
      <webElementGuid>4b562db7-6402-47e9-9ff1-1cd02589d286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KITS')]</value>
      <webElementGuid>dd9597e8-6eb8-4bc4-ae81-28b9188b06cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COILS'])[1]/following::a[1]</value>
      <webElementGuid>03608970-9b28-47fd-a561-735f439b0023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERSTATE &amp; INTERNATIONAL E-LIQUIDS'])[1]/following::a[2]</value>
      <webElementGuid>74a52117-cfb9-4cb4-bf26-7a45f1e7c8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MODS'])[1]/preceding::a[1]</value>
      <webElementGuid>cc5d5837-d84d-4020-9e4b-734c404513e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TANKS'])[1]/preceding::a[2]</value>
      <webElementGuid>5a7092bf-007b-4aaf-a5ad-30105fe8207a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KITS']/parent::*</value>
      <webElementGuid>90389905-a84c-45f4-80e0-57f3f524329e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collections/complete-kits')]</value>
      <webElementGuid>a588998a-5089-48ad-b0ab-d85629301b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>18a3b7fe-10a0-4b28-b4f5-ad541347c685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/complete-kits' and (text() = '
            KITS
          ' or . = '
            KITS
          ')]</value>
      <webElementGuid>969719fb-753a-4331-97de-6163eac460db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
