<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BLOGS</name>
   <tag></tag>
   <elementGuidId>3bcfd0e8-65d3-41c8-9623-a4947d6d69ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SiteNav']/li[13]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36ac6ac2-ae5a-4af8-bfee-0b8a822aad6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blogs/new-blogs</value>
      <webElementGuid>1aee4065-761b-419c-bf8d-bbc04fe91935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--main</value>
      <webElementGuid>8f19d382-a972-4375-85a8-8c00468fb5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            BLOGS
          </value>
      <webElementGuid>10f35583-db18-4beb-a57b-bdb019b5b4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteNav&quot;)/li[13]/a[@class=&quot;site-nav__link site-nav__link--main&quot;]</value>
      <webElementGuid>83623d15-d56a-467d-8dd6-2ea562605071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SiteNav']/li[13]/a</value>
      <webElementGuid>caf6173e-93a5-4e39-a749-ebebafa7298e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BLOGS')]</value>
      <webElementGuid>2bd97e6e-a593-4651-b194-7d09dc15ffdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STORE LOCATOR'])[1]/following::a[1]</value>
      <webElementGuid>0ca6ea63-089a-40b5-89af-48f495e616c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VS STANDARD CONCENTRATES'])[1]/following::a[2]</value>
      <webElementGuid>a4265f01-2fb6-4dde-b090-4623d7d05f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nicotine Script'])[1]/preceding::a[1]</value>
      <webElementGuid>a6b1b517-abc1-4268-8c01-06358b298cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADULT PRODUCTS'])[1]/preceding::a[2]</value>
      <webElementGuid>2e74f41d-739a-4bd9-9bba-ddccd9769089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BLOGS']/parent::*</value>
      <webElementGuid>008d7ccf-09f3-4bf4-ba53-e5cb6df1ea6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/blogs/new-blogs')]</value>
      <webElementGuid>bcef77b5-169e-4bed-bc6a-3ae5150e9df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/a</value>
      <webElementGuid>ca3a2e5b-58a5-4b18-bdad-b6f371cc639a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blogs/new-blogs' and (text() = '
            BLOGS
          ' or . = '
            BLOGS
          ')]</value>
      <webElementGuid>ac5d1b1c-ed17-40d4-ab68-c5afbce262ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
